{
	"openapi": "3.0.1",
	"info": {
		"version": "1.0.0",
		"title": "Drink Master",
		"description": "Drink Master API",
		"contact": {
			"email": "drink-master-backend@ukr.net"
		},
		"license": {
			"name": "MIT",
			"url": "https://opensource.org/licenses/MIT"
		}
	},
	"consumes": ["application/json", "multipart/form-data"],
	"produces": ["application/json"],
	"servers": [{ "url": "http://localhost:3000" }],
	"paths": {
		"/users/register": {
			"post": {
				"summary": "User Registration",
				"tags": ["users"],
				"requestBody": {
					"content": {
						"multipart/form-data": {
							"schema": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"email": {
										"type": "string",
										"format": "email"
									},
									"password": {
										"type": "string",
										"minLength": 6
									}
								},
								"required": ["name", "email", "password"]
							}
						}
					},
					"description": "Request for user registration",
					"required": true
				},
				"responses": {
					"201": {
						"description": "Successful user registration",
						"content": {
							"application/json": {
								"example": {
									"user": {
										"email": "user@example.com",
										"name": "John Doe",
										"avatarURL": "https://example.com/avatar.png"
									}
								}
							}
						}
					},
					"400": {
						"description": "Validation error or missing required fields"
					},
					"409": {
						"description": "Conflict: Email in use"
					}
				}
			}
		},
		"/users/login": {
			"post": {
				"summary": "User Login",
				"tags": ["users"],
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/authenticationRequest"
							}
						}
					},
					"description": "Request for user login",
					"required": true
				},
				"responses": {
					"200": {
						"description": "Successful user login",
						"content": {
							"application/json": {
								"example": {
									"token": "<your_token_jwt>",
									"user": {
										"id": "12345",
										"email": "user@example.com",
										"name": "John Doe"
									}
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized: Email or password is wrong"
					}
				}
			}
		},
		"/users/current": {
			"get": {
				"summary": "Get Current User",
				"tags": ["users"],
				"security": [
					{
						"Bearer": []
					}
				],
				"responses": {
					"200": {
						"description": "Successful retrieval of current user",
						"content": {
							"application/json": {
								"example": {
									"user": {
										"id": "12345",
										"email": "user@example.com",
										"name": "John Doe"
									}
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized: Not authorized"
					}
				}
			}
		},
		"/users/logout": {
			"post": {
				"summary": "User Logout",
				"tags": ["users"],
				"security": [
					{
						"Bearer": []
					}
				],
				"responses": {
					"204": {
						"description": "Successful user logout",
						"content": {
							"application/json": {
								"example": {
									"message": "Logout successful"
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized: Not authorized"
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"RegistrationResponse": {
				"type": "object",
				"properties": {
					"email": {
						"type": "string",
						"format": "email"
					},
					"name": {
						"type": "string"
					},
					"avatarURL": {
						"type": "string"
					}
				}
			},
			"RegistrationRequest": {
				"type": "object",
				"required": ["email", "password"],
				"properties": {
					"email": {
						"type": "string",
						"description": "User's email",
						"format": "email"
					},
					"password": {
						"type": "string",
						"description": "User's password",
						"example": "qwerty123"
					}
				}
			},

			"authenticationRequest": {
				"type": "object",
				"properties": {
					"email": {
						"type": "string",
						"description": "User's email",
						"format": "email"
					},
					"password": {
						"type": "string",
						"description": "User's password"
					}
				},
				"required": ["email", "password"]
			},
			"authenticationResponse": {
				"type": "object",
				"properties": {
					"token": {
						"type": "string"
					},
					"user": {
						"type": "object",
						"properties": {
							"id": {
								"type": "string"
							},
							"email": {
								"type": "string"
							},
							"name": {
								"type": "string"
							}
						}
					}
				}
			}
		},
		"securitySchemes": {
			"Bearer": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		}
	}
}
